informal_markers = [
    "absolutely",
    "anyway",
    "like",
    "right",
    "actually",
    "as i was saying",
    "fine",
    "for a start",
    "kind of",
    "ok",
    "sort of",
    "on top of that",
    "to be honest",
    "truth be told",
    "whats more",
    "what's more",
    "you know",
    "in my opinion",
    "okay",
    "even so",
    "mind you",
    "for a start",
    "as i say",
]

formal_markers = [
    "as a result",
    "for example",
    "furthermore",
    "in addition",
    "in conclusion",
    "moreover",
    "nevertheless",
    "such as",
    "on the other hand",
    "however",
    "alternatively",
    "as a consequence",
    "firstly",
    "secondly",
    "quite"
]
